"""Starting looks. Each preset lists only the knobs it changes from the
defaults in spec.KNOBS; applying one resets every other look knob."""

from collections import OrderedDict

PRESETS = OrderedDict([
    ("Default", {}),

    ("Anamorphic Blue", {
        "element_aspect": 0.6,
        "glow_color": (0.75, 0.85, 1.0),
        "glow_intensity": 0.4,
        "core_color": (0.9, 0.95, 1.0),
        "glint_intensity": 0.15,
        "glint_fine": 0.0,
        "streak_intensity": 1.6,
        "streak_length": 1.6,
        "streak_thickness": 2.5,
        "streak_glow": 1.4,
        "streak_color": (0.3, 0.55, 1.0),
        "ring_intensity": 0.03,
        "ring_spectral": 0.3,
        "ring_color": (0.6, 0.8, 1.0),
        "ghost_blades": 0,
        "ghost_roundness": 1.0,
        "ghost_softness": 0.15,
        "ghost_hue_random": 0.15,
        "ghost_color": (0.55, 0.75, 1.0),
        "ghost_count": 7,
        "ghost_size": 0.08,
        "spectral_enable": False,
    }),

    ("Sun Starburst", {
        "glow_size": 0.15,
        "glow_intensity": 0.7,
        "glow_color": (1.0, 0.85, 0.6),
        "core_intensity": 8.0,
        "core_size": 0.02,
        "glint_count": 18,
        "glint_intensity": 1.2,
        "glint_length": 0.6,
        "glint_width": 2.5,
        "glint_fine": 0.9,
        "streak_intensity": 0.2,
        "ring_enable": False,
        "ghost_count": 14,
        "ghost_size": 0.035,
        "ghost_intensity": 0.15,
        "spectral_count": 20,
        "spectral_intensity": 0.7,
        "spectral_length": 0.05,
    }),

    ("Sci-Fi Hoop", {
        "glow_color": (0.7, 0.85, 1.0),
        "glint_count": 8,
        "glint_intensity": 0.4,
        "streak_intensity": 1.0,
        "streak_length": 1.4,
        "streak_color": (0.35, 0.6, 1.0),
        "ring_intensity": 0.15,
        "ring_radius": 0.42,
        "ring_thickness": 0.03,
        "ring_spectral": 1.0,
        "ring_axis_pos": 1.0,
        "ring_arc": 0.35,
        "ghost_blades": 8,
        "ghost_hollow": 0.85,
        "ghost_chroma": 0.12,
        "ghost_intensity": 0.2,
        "spectral_orient": 1.0,
        "spectral_count": 8,
        "spectral_length": 0.06,
        "spectral_width": 5.0,
        "spectral_offset": 0.12,
    }),

    ("Vintage Warm", {
        "master_tint": (1.0, 0.9, 0.75),
        "glow_color": (1.0, 0.65, 0.35),
        "glow_size": 0.14,
        "glow_falloff": 0.8,
        "glint_count": 6,
        "glint_intensity": 0.3,
        "glint_width": 4.0,
        "glint_fine": 0.0,
        "streak_enable": False,
        "ring_intensity": 0.03,
        "ring_spectral": 0.4,
        "ring_color": (1.0, 0.75, 0.5),
        "ghost_blades": 0,
        "ghost_roundness": 1.0,
        "ghost_softness": 0.35,
        "ghost_hollow": 0.1,
        "ghost_hue_random": 0.15,
        "ghost_color": (1.0, 0.7, 0.4),
        "ghost_intensity": 0.18,
        "ghost_count": 7,
        "ghost_size": 0.09,
        "spectral_enable": False,
    }),

    ("Subtle Practical", {
        "master_intensity": 0.6,
        "glow_size": 0.05,
        "core_size": 0.008,
        "glint_count": 8,
        "glint_length": 0.12,
        "glint_fine": 0.2,
        "streak_enable": False,
        "ring_enable": False,
        "ghost_count": 5,
        "ghost_intensity": 0.06,
        "ghost_size": 0.04,
        "spectral_enable": False,
    }),

    ("Hexagon Iris", {
        "glint_intensity": 0.4,
        "streak_enable": False,
        "ring_intensity": 0.02,
        "ghost_count": 16,
        "ghost_blades": 6,
        "ghost_roundness": 0.0,
        "ghost_hollow": 0.1,
        "ghost_chroma": 0.08,
        "ghost_softness": 0.05,
        "ghost_intensity": 0.16,
        "ghost_size": 0.08,
        "ghost_spread_min": -0.2,
        "ghost_spread_max": 2.3,
    }),

    ("Cross Star", {
        "glow_size": 0.04,
        "glint_enable": False,
        "streak_count": 2,
        "streak_angle": 45.0,
        "streak_length": 0.35,
        "streak_thickness": 1.2,
        "streak_intensity": 1.2,
        "streak_color": (1.0, 0.95, 0.9),
        "ring_enable": False,
        "ghost_count": 4,
        "ghost_intensity": 0.05,
        "spectral_count": 16,
        "spectral_offset": 0.03,
        "spectral_length": 0.025,
    }),
])
